name: sispadu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dio: ^5.3.2
  logger: ^2.0.2
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  formz: ^0.6.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  go_router: ^10.1.2
  flutter_native_splash: ^2.2.16
  responsive_framework: ^1.1.1
  dropdown_search: ^5.0.6
  infinite_scroll_pagination: ^4.0.0
  intl: 0.19.0
  bloc_concurrency: ^0.2.2
  flutter_speed_dial: ^7.0.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  extended_image: ^8.1.1
  flutter_dotenv: ^5.1.0
  lottie: ^2.6.0
  esc_pos_utils: ^1.1.0
  # print_bluetooth_thermal: ^1.1.1
  onesignal_flutter: ^5.0.4
  fl_chart: ^0.67.0
  primer_progress_bar: ^0.4.1
  shimmer: ^3.0.0
  font_awesome_flutter: '>=10.7.0'
  package_info_plus: ^8.0.0
  app_links: ^6.1.4
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  open_file: ^3.5.7
  photo_view: ^0.15.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - .env
